export const DNR_PRIORITIES = {
  FAIL_CLOSED_STRIP: 1000,
  VIRTUAL_COOKIE_PATH: 900,
  VIRTUAL_COOKIE_ROOT: 800,
  VIRTUAL_COOKIE_SITE: 750,
  NATIVE_SET_COOKIE_STRIP: 700,
  RESERVED: 100,
} as const;

export type DnrPriorityName = keyof typeof DNR_PRIORITIES;
